#!/bin/sh

set -e

check_version() {
  local cmd=$1
  $cmd --version | cut -d ' ' -f 2 | cut -d '.' -f 1  
}

install_doit() {
  if $(uname -a | grep --fixed-strings --quiet Ubuntu); then
    sudo apt-get install --yes python3-doit
  elif [ $(check_version python) -ge 3 ]; then
    python -m pip install doit
    python -m pip install typing_extensions
  elif [ $(check_version python3) -ge 3 ]; then
    python3 -m pip install doit
    python3 -m pip install typing_extensions
  elif type brew > /dev/null; then
    brew install python
    python -m pip install doit
  else
    echo "Homebrew is required. Please install it manually."
    echo "https://brew.sh/"
    exit 1
  fi
}

bootstrap() {
cp -n myconfig.example.py myconfig.py || echo "myconfig.py existed, will use it" 
if type doit > /dev/null; then
  doit
else
  install_doit
  doit
fi
}

install_dotfiles() {
  # Currently just call bootstrap,
  # since doit can be installed via apt in gitpod in 10 seconds,
  # as I have tested before.
  bootstrap
}

main() {
  if [ INGITPOD = false ]; then
    bootstrap
  else
    install_dotfiles
  fi
}

main
