#!/bin/sh

set -e

check_version() {
  local cmd=$1
  $cmd --version | cut --delimiter ' ' --fields 2 | cut --delimiter '.' --fields 1,2
}

install_doit() {
  if [ $(uname --kernel--version | grep --fixed-strings --quiet Ubuntu)]; then
    sudo apt-get install --yes python3-doit
  elif [ $(check_version python) -ge 3.10 ]; then
    python -m pip install doit
  elif [ $(check_version python3) -ge 3.10]; then
    python3 -m pip install doit
  elif type brew > /dev/null; then
    brew install python
    python -m pip install doit
  else
    echo "Homebrew is required. Please install it manually."
    echo "https://brew.sh/"
    exit 1
  fi
}

bootstrap() {
if type doit > /dev/null; then
  doit
else
  install_doit
  doit
fi
}

install_dotfiles() {
  # Currently just call bootstrap,
  # since doit can be installed via apt in gitpod in 10 seconds,
  # as I have tested before.
  bootstrap
}

main() {
  if [ INGITPOD = false ]; then
    bootstrap
  else
    install_dotfiles
  fi
}

main
