name: Check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dev tools
        run: pip install -r requirements-dev.txt

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Install shfmt
        run: |
          version=v3.10.0
          curl -fsSL "https://github.com/mvdan/sh/releases/download/${version}/shfmt_${version}_linux_amd64" \
            -o /usr/local/bin/shfmt
          chmod +x /usr/local/bin/shfmt

      - name: Run checks
        run: sh script/check
